version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "--verbose", "start-dev", "--import-realm" ]
    environment:
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
      KC_PROXY: edge
      KC_HTTP_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        source: ./target
        target: /opt/keycloak/providers:Z
      - type: bind
        source: ./moodle-realm.json
        target: /opt/keycloak/data/import/moodle-realm.json:Z
    ports:
      - '8080:8080'
      - '8787:8787'
